export * from './man-clothe/man-clothe.component';
export * from './women-clothe/women-clothe.component';
export * from './child-clothe/child-clothe.component';
export * from './child-clothe/bodysuit/bodysuit.component';
export * from './child-clothe/t-shirt/t-shirt.component';
export * from './women-clothe/dress/dress.component';
export * from './women-clothe/skirt/skirt.component';
export * from './man-clothe/jeans/jeans.component';
export * from './man-clothe/shorts/shorts.component';
